//! Gold Standard Parity Tests — Phase 8: 8 modules with zero oracle coverage
//!
//! Verification chain: scipy/numpy/sympy/analytical → tambear CPU
//!
//! Modules covered:
//!   1. signal_processing.rs — FFT, DCT, convolution, windows
//!   2. series_accel.rs — Aitken, Wynn, Richardson, Euler, Cesaro
//!   3. multi_adic.rs — p-adic valuation, norm, distance, digits
//!   4. number_theory.rs — primality, factorization, CRT, modular arithmetic
//!   5. stochastic.rs — GBM moments, Black-Scholes, OU, Markov chains
//!   6. physics.rs — SHO, Kepler, damped oscillator, constants
//!   7. fold_irreversibility.rs — trailing ones, Collatz odd steps
//!   8. rng.rs — distribution moments (statistical, large-sample)
//!
//! Expected values generated by Python scripts in research/gold_standard/

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

fn assert_close(name: &str, got: f64, expected: f64, tol: f64) {
    let abs_diff = (got - expected).abs();
    let rel_diff = if expected.abs() > 1e-15 {
        abs_diff / expected.abs()
    } else {
        abs_diff
    };
    assert!(
        abs_diff < tol || rel_diff < tol,
        "{}: got {:.15e}, expected {:.15e}, abs_diff={:.2e}, rel_diff={:.2e}, tol={:.0e}",
        name, got, expected, abs_diff, rel_diff, tol
    );
}

fn assert_slices_close(name: &str, got: &[f64], expected: &[f64], tol: f64) {
    assert_eq!(
        got.len(),
        expected.len(),
        "{}: length mismatch: {} vs {}",
        name,
        got.len(),
        expected.len()
    );
    for (i, (&g, &e)) in got.iter().zip(expected.iter()).enumerate() {
        assert_close(&format!("{}[{}]", name, i), g, e, tol);
    }
}

// ===========================================================================
// 1. SIGNAL PROCESSING — verified against numpy.fft, scipy.signal
// ===========================================================================

mod signal_processing_parity {
    use super::*;
    use tambear::signal_processing::*;

    // ── FFT: DC signal → all energy at bin 0 ────────────────────────────

    #[test]
    fn fft_dc_8pt() {
        // numpy.fft.fft([1,1,1,1,1,1,1,1]) = [8, 0, 0, 0, 0, 0, 0, 0]
        let input: Vec<(f64, f64)> = vec![(1.0, 0.0); 8];
        let result = fft(&input);
        assert_close("fft_dc[0].re", result[0].0, 8.0, 1e-12);
        for i in 1..8 {
            assert_close(&format!("fft_dc[{}].re", i), result[i].0, 0.0, 1e-12);
            assert_close(&format!("fft_dc[{}].im", i), result[i].1, 0.0, 1e-12);
        }
    }

    // ── FFT: impulse → flat spectrum ────────────────────────────────────

    #[test]
    fn fft_impulse_8pt() {
        // numpy.fft.fft([1,0,0,0,0,0,0,0]) = [1,1,1,1,1,1,1,1]
        let mut input = vec![(0.0, 0.0); 8];
        input[0] = (1.0, 0.0);
        let result = fft(&input);
        for i in 0..8 {
            assert_close(&format!("fft_impulse[{}].re", i), result[i].0, 1.0, 1e-12);
            assert_close(&format!("fft_impulse[{}].im", i), result[i].1, 0.0, 1e-12);
        }
    }

    // ── FFT: [1,2,3,4] ─────────────────────────────────────────────────

    #[test]
    fn fft_1234() {
        // numpy.fft.fft([1,2,3,4])
        let input: Vec<(f64, f64)> = vec![(1.0, 0.0), (2.0, 0.0), (3.0, 0.0), (4.0, 0.0)];
        let result = fft(&input);
        let expected_re = [10.0, -2.0, -2.0, -2.0];
        let expected_im = [0.0, 2.0, 0.0, -2.0];
        for i in 0..4 {
            assert_close(&format!("fft_1234[{}].re", i), result[i].0, expected_re[i], 1e-12);
            assert_close(&format!("fft_1234[{}].im", i), result[i].1, expected_im[i], 1e-12);
        }
    }

    // ── IFFT roundtrip ──────────────────────────────────────────────────

    #[test]
    fn ifft_roundtrip() {
        let original = vec![
            (1.0, 0.0), (-1.0, 0.0), (2.0, 0.0), (-2.0, 0.0),
            (3.0, 0.0), (-3.0, 0.0), (0.5, 0.0), (1.5, 0.0),
        ];
        let forward = fft(&original);
        let back = ifft(&forward);
        for i in 0..8 {
            assert_close(&format!("ifft_rt[{}].re", i), back[i].0, original[i].0, 1e-12);
            assert_close(&format!("ifft_rt[{}].im", i), back[i].1, 0.0, 1e-12);
        }
    }

    // ── rfft ────────────────────────────────────────────────────────────

    #[test]
    fn rfft_8pt() {
        let input: Vec<f64> = (1..=8).map(|x| x as f64).collect();
        let result = rfft(&input);
        // rfft returns N/2+1 = 5 coefficients
        assert_eq!(result.len(), 5, "rfft should return N/2+1 coefficients");
        // DC: sum of all = 36
        assert_close("rfft[0].re", result[0].0, 36.0, 1e-12);
        assert_close("rfft[0].im", result[0].1, 0.0, 1e-12);
    }

    // ── Parseval's theorem ──────────────────────────────────────────────

    #[test]
    fn parseval_theorem() {
        let input: Vec<(f64, f64)> = (1..=8).map(|x| (x as f64, 0.0)).collect();
        let spectrum = fft(&input);
        let energy_time: f64 = input.iter().map(|c| c.0 * c.0 + c.1 * c.1).sum();
        let energy_freq: f64 = spectrum.iter().map(|c| c.0 * c.0 + c.1 * c.1).sum::<f64>()
            / input.len() as f64;
        assert_close("parseval", energy_time, energy_freq, 1e-10);
    }

    // ── Convolution ─────────────────────────────────────────────────────

    #[test]
    fn convolve_3x3_matches_numpy() {
        // numpy.convolve([1,2,3], [0.5,1.0,0.5]) = [0.5, 2.0, 4.0, 4.0, 1.5]
        let a = [1.0, 2.0, 3.0];
        let b = [0.5, 1.0, 0.5];
        let result = convolve(&a, &b);
        let expected = [0.5, 2.0, 4.0, 4.0, 1.5];
        assert_eq!(result.len(), 5);
        assert_slices_close("convolve_3x3", &result, &expected, 1e-10);
    }

    #[test]
    fn convolve_4x2_matches_numpy() {
        // numpy.convolve([1,0,-1,2], [1,1]) = [1, 1, -1, 1, 2]
        let a = [1.0, 0.0, -1.0, 2.0];
        let b = [1.0, 1.0];
        let result = convolve(&a, &b);
        let expected = [1.0, 1.0, -1.0, 1.0, 2.0];
        assert_eq!(result.len(), 5);
        assert_slices_close("convolve_4x2", &result, &expected, 1e-10);
    }

    // ── DCT-II ──────────────────────────────────────────────────────────

    #[test]
    fn dct2_4pt_matches_scipy() {
        // scipy.fftpack.dct([1,2,3,4], type=2, norm=None)
        let input = [1.0, 2.0, 3.0, 4.0];
        let result = dct2(&input);
        let expected = [20.0, -6.30864405979789921730, 0.0, -4.48341529167965102687e-1];
        assert_eq!(result.len(), 4);
        assert_close("dct2[0]", result[0], expected[0], 1e-12);
        assert_close("dct2[1]", result[1], expected[1], 1e-10);
        assert_close("dct2[2]", result[2], expected[2], 1e-12);
        assert_close("dct2[3]", result[3], expected[3], 1e-10);
    }

    // ── Window functions ────────────────────────────────────────────────

    #[test]
    fn hann_window_matches_scipy() {
        let w = window_hann(8);
        // scipy.signal.windows.hann(8, sym=True)
        // Endpoints should be 0, peak at center
        assert_close("hann[0]", w[0], 0.0, 1e-14);
        assert_close("hann[7]", w[7], 0.0, 1e-14);
        // Middle values should be symmetric
        assert_close("hann symmetry", w[1], w[7 - 1], 1e-14);
        assert_close("hann symmetry", w[2], w[7 - 2], 1e-14);
        // Sum test: Hann window sum ≈ (N-1)/2 = 3.5
        let sum: f64 = w.iter().sum();
        assert_close("hann_sum", sum, 3.5, 0.1);
    }

    #[test]
    fn hamming_window_matches_scipy() {
        let w = window_hamming(8);
        // Hamming window has non-zero endpoints (0.08)
        assert_close("hamming[0]", w[0], 0.08, 1e-10);
        assert_close("hamming[7]", w[7], 0.08, 1e-10);
    }

    #[test]
    fn blackman_window_matches_scipy() {
        let w = window_blackman(8);
        // Blackman window endpoints should be ~0
        assert_close("blackman[0]", w[0], 0.0, 1e-10);
        assert_close("blackman[7]", w[7], 0.0, 1e-10);
    }

    #[test]
    fn bartlett_window_matches_scipy() {
        let w = window_bartlett(8);
        assert_close("bartlett[0]", w[0], 0.0, 1e-14);
        assert_close("bartlett[7]", w[7], 0.0, 1e-14);
        // Peak at center
        assert!(w[3] > 0.8);
        assert!(w[4] > 0.8);
    }

    // ── Autocorrelation ─────────────────────────────────────────────────

    #[test]
    fn autocorrelation_lag0_is_1() {
        let data: Vec<f64> = (0..64).map(|i| (i as f64 * 0.1).sin()).collect();
        let acf = autocorrelation(&data, 10);
        assert_close("acf[0]", acf[0], 1.0, 1e-12);
        // ACF should decay for a sine wave
        assert!(acf[1].abs() < 1.0);
    }
}

// ===========================================================================
// 2. SERIES ACCELERATION — verified against known series limits
// ===========================================================================

mod series_accel_parity {
    use super::*;
    use tambear::series_accel::*;

    const PI_OVER_4: f64 = std::f64::consts::FRAC_PI_4;
    const PI_SQ_OVER_6: f64 = 1.6449340668482264;
    const LN_2: f64 = std::f64::consts::LN_2;

    // ── Partial sums ────────────────────────────────────────────────────

    #[test]
    fn partial_sums_basic() {
        let terms = vec![1.0, 2.0, 3.0, 4.0];
        let sums = partial_sums(&terms);
        assert_slices_close("partial_sums", &sums, &[1.0, 3.0, 6.0, 10.0], 1e-15);
    }

    // ── Cesaro: Grandi's series → 1/2 ───────────────────────────────────

    #[test]
    fn cesaro_grandi_converges_to_half() {
        // 1 - 1 + 1 - 1 + ... Cesaro sum should approach 0.5
        let terms: Vec<f64> = (0..100).map(|n| if n % 2 == 0 { 1.0 } else { -1.0 }).collect();
        let sums = partial_sums(&terms);
        let cs = cesaro_sum(&sums);
        assert_close("cesaro_grandi", cs, 0.5, 0.01);
    }

    // ── Aitken on Leibniz ───────────────────────────────────────────────

    #[test]
    fn aitken_leibniz_improves_convergence() {
        let n = 20;
        let terms: Vec<f64> = (0..n).map(|k| {
            (-1.0f64).powi(k as i32) / (2 * k + 1) as f64
        }).collect();
        let sums = partial_sums(&terms);
        let raw_error = (sums[n - 1] - PI_OVER_4).abs();
        let accel = aitken_delta2(&sums);
        let accel_error = (accel.last().unwrap() - PI_OVER_4).abs();
        // Aitken should reduce error by at least 100x
        assert!(
            accel_error < raw_error / 10.0,
            "Aitken should improve: raw_err={:.2e}, accel_err={:.2e}",
            raw_error, accel_error
        );
    }

    // ── Wynn epsilon on Leibniz ─────────────────────────────────────────

    #[test]
    fn wynn_leibniz_converges() {
        let n = 20;
        let terms: Vec<f64> = (0..n).map(|k| {
            (-1.0f64).powi(k as i32) / (2 * k + 1) as f64
        }).collect();
        let sums = partial_sums(&terms);
        let estimate = wynn_epsilon(&sums);
        assert_close("wynn_leibniz", estimate, PI_OVER_4, 1e-6);
    }

    // ── Wynn epsilon on ln(2) ───────────────────────────────────────────

    #[test]
    fn wynn_ln2_converges() {
        let n = 20;
        let terms: Vec<f64> = (0..n).map(|k| {
            (-1.0f64).powi(k as i32) / (k + 1) as f64
        }).collect();
        let sums = partial_sums(&terms);
        let estimate = wynn_epsilon(&sums);
        assert_close("wynn_ln2", estimate, LN_2, 1e-6);
    }

    // ── Richardson extrapolation on Basel ────────────────────────────────

    #[test]
    fn richardson_basel() {
        // Basel series partial sums at N=5,10,20,40 with ratio=2, order=1
        let approxs: Vec<f64> = [5, 10, 20, 40].iter().map(|&n| {
            (1..=n).map(|k| 1.0 / (k * k) as f64).sum::<f64>()
        }).collect();
        let estimate = richardson_extrapolate(&approxs, 2.0, 1);
        // Python oracle: error ≈ 3e-7
        assert_close("richardson_basel", estimate, PI_SQ_OVER_6, 1e-5);
    }

    // ── Euler transform on ln(2) ────────────────────────────────────────

    #[test]
    fn euler_transform_ln2() {
        let n = 20;
        let terms: Vec<f64> = (0..n).map(|k| {
            (-1.0f64).powi(k as i32) / (k + 1) as f64
        }).collect();
        let estimate = euler_transform(&terms);
        // Euler transform should be close to ln(2)
        assert_close("euler_ln2", estimate, LN_2, 1e-3);
    }

    // ── Streaming Wynn ──────────────────────────────────────────────────

    #[test]
    fn streaming_wynn_leibniz() {
        let mut sw = StreamingWynn::new(40);
        for k in 0..30 {
            let term = (-1.0f64).powi(k) / (2 * k + 1) as f64;
            sw.push(term);
        }
        assert_close("streaming_wynn_leibniz", sw.estimate(), PI_OVER_4, 1e-6);
    }
}

// ===========================================================================
// 3. MULTI-ADIC — verified against known identities (bit-perfect)
// ===========================================================================

mod multi_adic_parity {
    use super::*;
    use tambear::multi_adic::*;

    // ── p-adic valuation ────────────────────────────────────────────────

    #[test]
    fn valuation_known_values() {
        assert_eq!(valuation(12, 2), 2);   // 12 = 2^2 * 3
        assert_eq!(valuation(12, 3), 1);
        assert_eq!(valuation(12, 5), 0);
        assert_eq!(valuation(8, 2), 3);    // 8 = 2^3
        assert_eq!(valuation(1, 2), 0);
        assert_eq!(valuation(0, 2), u32::MAX);
        assert_eq!(valuation(32, 2), 5);   // 2^5
        assert_eq!(valuation(243, 3), 5);  // 3^5
        assert_eq!(valuation(3125, 5), 5); // 5^5
        assert_eq!(valuation(2520, 2), 3); // 2520 = 2^3 * 3^2 * 5 * 7
        assert_eq!(valuation(2520, 3), 2);
        assert_eq!(valuation(2520, 5), 1);
        assert_eq!(valuation(2520, 7), 1);
    }

    // ── p-adic norm ─────────────────────────────────────────────────────

    #[test]
    fn norm_known_values() {
        assert_close("|8|_2", p_adic_norm(8, 2), 0.125, 1e-15);
        assert_close("|9|_3", p_adic_norm(9, 3), 1.0 / 9.0, 1e-15);
        assert_close("|7|_2", p_adic_norm(7, 2), 1.0, 1e-15);
        assert_close("|0|_2", p_adic_norm(0, 2), 0.0, 1e-15);
        assert_close("|25|_5", p_adic_norm(25, 5), 0.04, 1e-15);
    }

    // ── p-adic distance ─────────────────────────────────────────────────

    #[test]
    fn distance_known_values() {
        assert_close("d_2(0,8)", p_adic_distance(0, 8, 2), 0.125, 1e-15);
        assert_close("d_2(0,4)", p_adic_distance(0, 4, 2), 0.25, 1e-15);
        assert_close("d_2(7,7)", p_adic_distance(7, 7, 2), 0.0, 1e-15);
        assert_close("d_2(6,12)", p_adic_distance(6, 12, 2), 0.5, 1e-15);
    }

    // ── Ultrametric inequality ──────────────────────────────────────────

    #[test]
    fn ultrametric_inequality_holds() {
        for &p in &[2u64, 3, 5] {
            for &(a, b, c) in &[(1u64, 3, 5), (2, 6, 10), (7, 15, 31)] {
                let dac = p_adic_distance(a, c, p);
                let dab = p_adic_distance(a, b, p);
                let dbc = p_adic_distance(b, c, p);
                assert!(
                    dac <= dab.max(dbc) + 1e-15,
                    "Ultrametric failed p={}: d({},{})={} > max(d({},{})={}, d({},{})={})",
                    p, a, c, dac, a, b, dab, b, c, dbc
                );
            }
        }
    }

    // ── p-adic digits roundtrip ─────────────────────────────────────────

    #[test]
    fn digits_roundtrip() {
        for &p in &[2u64, 3, 5, 7, 10] {
            for &n in &[0u64, 1, 42, 100, 12345, 999999] {
                let digits = p_adic_digits(n, p, 64);
                let reconstructed = from_p_adic_digits(&digits, p);
                assert_eq!(reconstructed, n, "roundtrip failed n={}, p={}", n, p);
            }
        }
    }

    // ── Known digit expansions ──────────────────────────────────────────

    #[test]
    fn known_digit_expansions() {
        // 13 in binary: 1101 → [1, 0, 1, 1] (low-order first)
        assert_eq!(p_adic_digits(13, 2, 10), vec![1, 0, 1, 1]);
        // 23 in base 3: [2, 1, 2]
        assert_eq!(p_adic_digits(23, 3, 10), vec![2, 1, 2]);
    }

    // ── Multi-adic profile ──────────────────────────────────────────────

    #[test]
    fn profile_known_numbers() {
        // 60 = 2^2 * 3 * 5
        let p60 = MultiAdicProfile::default_of(60);
        assert_eq!(p60.v(2), Some(2));
        assert_eq!(p60.v(3), Some(1));
        assert_eq!(p60.v(5), Some(1));
        assert_eq!(p60.v(7), Some(0));

        // 11 is coprime to {2,3,5,7}
        let p11 = MultiAdicProfile::default_of(11);
        assert!(p11.is_coprime_to_all());

        // 2520 = 2^3 * 3^2 * 5 * 7
        let p2520 = MultiAdicProfile::default_of(2520);
        assert_eq!(p2520.total_weight(), 7);
    }

    // ── Batch profiles ──────────────────────────────────────────────────

    #[test]
    fn batch_profiles_10_5() {
        let primes = [2u64, 3, 5];
        let result = batch_profiles(10, 5, &primes);
        // n=10=2*5: v2=1, v3=0, v5=1
        assert_eq!(result[0], 1);
        assert_eq!(result[1], 0);
        assert_eq!(result[2], 1);
        // n=12=2^2*3: v2=2, v3=1, v5=0
        assert_eq!(result[6], 2);
        assert_eq!(result[7], 1);
        assert_eq!(result[8], 0);
    }
}

// ===========================================================================
// 4. NUMBER THEORY — verified against sympy (bit-perfect)
// ===========================================================================

mod number_theory_parity {
    use super::*;
    use tambear::number_theory::*;

    // ── Primality ───────────────────────────────────────────────────────

    #[test]
    fn primes_match_sympy() {
        let known_primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47,
            97, 101, 1009, 10007, 100003, 1000003, 999999937u64];
        for &p in &known_primes {
            assert!(is_prime(p), "{} should be prime", p);
        }
    }

    #[test]
    fn composites_match_sympy() {
        let known_composites = [4, 6, 8, 9, 10, 15, 21, 25, 100, 1001, 999999938u64];
        for &c in &known_composites {
            assert!(!is_prime(c), "{} should be composite", c);
        }
    }

    // ── Sieve ───────────────────────────────────────────────────────────

    #[test]
    fn sieve_to_100() {
        let primes = sieve(100);
        assert_eq!(primes.len(), 25); // pi(100) = 25
        assert_eq!(primes[0], 2);
        assert_eq!(primes[24], 97);
    }

    // ── Next prime ──────────────────────────────────────────────────────

    #[test]
    fn next_prime_matches_sympy() {
        assert_eq!(next_prime(1), 2);
        assert_eq!(next_prime(2), 3);
        assert_eq!(next_prime(10), 11);
        assert_eq!(next_prime(100), 101);
    }

    // ── Prime counting ──────────────────────────────────────────────────

    #[test]
    fn prime_count_matches_sympy() {
        assert_eq!(prime_count(10), 4);    // {2,3,5,7}
        assert_eq!(prime_count(100), 25);
        assert_eq!(prime_count(1000), 168);
    }

    // ── Factorization ───────────────────────────────────────────────────

    #[test]
    fn factorize_matches_sympy() {
        assert_eq!(factorize(12), vec![(2, 2), (3, 1)]);
        assert_eq!(factorize(60), vec![(2, 2), (3, 1), (5, 1)]);
        assert_eq!(factorize(2520), vec![(2, 3), (3, 2), (5, 1), (7, 1)]);
        // 65536 = 2^16
        assert_eq!(factorize(65536), vec![(2, 16)]);
        // 999999937 is prime
        assert_eq!(factorize(999999937), vec![(999999937, 1)]);
    }

    // ── Euler totient ───────────────────────────────────────────────────

    #[test]
    fn euler_totient_matches_sympy() {
        assert_eq!(euler_totient(1), 1);
        assert_eq!(euler_totient(2), 1);
        assert_eq!(euler_totient(6), 2);
        assert_eq!(euler_totient(10), 4);
        assert_eq!(euler_totient(12), 4);
        assert_eq!(euler_totient(36), 12);
        assert_eq!(euler_totient(100), 40);
    }

    // ── Mobius function ─────────────────────────────────────────────────

    #[test]
    fn mobius_matches_sympy() {
        assert_eq!(mobius(1), 1);
        assert_eq!(mobius(2), -1);   // prime
        assert_eq!(mobius(3), -1);   // prime
        assert_eq!(mobius(4), 0);    // 2^2 — not squarefree
        assert_eq!(mobius(5), -1);
        assert_eq!(mobius(6), 1);    // 2*3
        assert_eq!(mobius(30), -1);  // 2*3*5 (3 prime factors)
    }

    // ── GCD and LCM ─────────────────────────────────────────────────────

    #[test]
    fn gcd_lcm_matches() {
        assert_eq!(gcd(12, 18), 6);
        assert_eq!(gcd(35, 49), 7);
        assert_eq!(gcd(100, 75), 25);
        assert_eq!(gcd(17, 13), 1); // coprime
        assert_eq!(lcm(12, 18), 36);
        assert_eq!(lcm(35, 49), 245);
    }

    // ── Modular exponentiation ──────────────────────────────────────────

    #[test]
    fn mod_pow_matches_sympy() {
        assert_eq!(mod_pow(2, 10, 1000), 24);     // 1024 mod 1000
        assert_eq!(mod_pow(7, 256, 13), mod_pow(7, 256, 13)); // self-consistent
        assert_eq!(mod_pow(2, 32, 1000000007), 294967268); // sympy verified
    }

    // ── Modular inverse ─────────────────────────────────────────────────

    #[test]
    fn mod_inverse_matches_sympy() {
        assert_eq!(mod_inverse(3, 7), Some(5));    // 3*5 = 15 ≡ 1 (mod 7)
        assert_eq!(mod_inverse(5, 13), Some(8));   // 5*8 = 40 ≡ 1 (mod 13)
        assert_eq!(mod_inverse(2, 4), None);       // gcd(2,4) ≠ 1
    }

    // ── CRT ─────────────────────────────────────────────────────────────

    #[test]
    fn crt_matches_sympy() {
        // x ≡ 2 (mod 3), x ≡ 3 (mod 5), x ≡ 2 (mod 7) → x = 23 (mod 105)
        let result = crt(&[2, 3, 2], &[3, 5, 7]).unwrap();
        assert_eq!(result.1, 105); // product of moduli
        assert_eq!(result.0 % 3, 2);
        assert_eq!(result.0 % 5, 3);
        assert_eq!(result.0 % 7, 2);
    }

    // ── Legendre symbol ─────────────────────────────────────────────────

    #[test]
    fn legendre_matches_sympy() {
        assert_eq!(legendre(1, 7), 1);
        assert_eq!(legendre(2, 7), 1);
        assert_eq!(legendre(3, 7), -1);
        assert_eq!(legendre(4, 7), 1);  // 4 = 2^2 ≡ QR
    }

    // ── Number-theoretic functions ──────────────────────────────────────

    #[test]
    fn num_divisors_matches_sympy() {
        assert_eq!(num_divisors(1), 1);
        assert_eq!(num_divisors(6), 4);
        assert_eq!(num_divisors(12), 6);
        assert_eq!(num_divisors(28), 6);
        assert_eq!(num_divisors(60), 12);
    }

    #[test]
    fn sum_divisors_perfect_numbers() {
        // Perfect numbers: sigma(n) = 2n
        assert_eq!(sum_divisors(6), 12);
        assert_eq!(sum_divisors(28), 56);
        assert_eq!(sum_divisors(496), 992);
    }

    #[test]
    fn divisors_sorted() {
        assert_eq!(divisors(12), vec![1, 2, 3, 4, 6, 12]);
        assert_eq!(divisors(28), vec![1, 2, 4, 7, 14, 28]);
    }

    // ── Continued fractions ─────────────────────────────────────────────

    #[test]
    fn continued_fraction_sqrt2() {
        // sqrt(2) = [1; 2, 2, 2, 2, ...]
        let cf = continued_fraction(std::f64::consts::SQRT_2, 10);
        assert_eq!(cf[0], 1);
        for i in 1..cf.len().min(8) {
            assert_eq!(cf[i], 2, "sqrt(2) cf[{}] should be 2, got {}", i, cf[i]);
        }
    }

    #[test]
    fn continued_fraction_golden_ratio() {
        // phi = [1; 1, 1, 1, ...]
        let phi = (1.0 + 5.0f64.sqrt()) / 2.0;
        let cf = continued_fraction(phi, 10);
        for i in 0..cf.len().min(8) {
            assert_eq!(cf[i], 1, "phi cf[{}] should be 1, got {}", i, cf[i]);
        }
    }
}

// ===========================================================================
// 5. STOCHASTIC — verified against analytical formulas and scipy
// ===========================================================================

mod stochastic_parity {
    use super::*;
    use tambear::stochastic::*;

    // ── GBM analytical moments ──────────────────────────────────────────

    #[test]
    fn gbm_expected_matches_formula() {
        // E[S(T)] = S0 * exp(mu*T)
        let s0 = 100.0;
        let mu = 0.05;
        let t = 1.0;
        let expected = 105.12710963760242; // scipy verified
        assert_close("gbm_expected", gbm_expected(s0, mu, t), expected, 1e-10);
    }

    #[test]
    fn gbm_variance_matches_formula() {
        // Var[S(T)] = S0^2 * exp(2*mu*T) * (exp(sigma^2*T) - 1)
        let s0 = 100.0;
        let mu = 0.05;
        let sigma = 0.2;
        let t = 1.0;
        let expected = 451.0288078157963; // scipy verified
        assert_close("gbm_variance", gbm_variance(s0, mu, sigma, t), expected, 1e-6);
    }

    // ── Black-Scholes ATM ───────────────────────────────────────────────

    #[test]
    fn black_scholes_atm_matches_scipy() {
        let (call_price, call_delta) = black_scholes(100.0, 100.0, 1.0, 0.05, 0.2, true);
        let (put_price, put_delta) = black_scholes(100.0, 100.0, 1.0, 0.05, 0.2, false);
        // scipy verified values — erfc upgrade gives near-machine-precision normal CDF
        assert_close("bs_call", call_price, 10.450583572185565, 1e-10);
        assert_close("bs_call_delta", call_delta, 0.6368306511756191, 1e-10);
        assert_close("bs_put", put_price, 5.573526022256971, 1e-10);
        assert_close("bs_put_delta", put_delta, -0.3631693488243809, 1e-10);
        // Put-call parity: C - P = S - K*exp(-rT)
        let parity = call_price - put_price - (100.0 - 100.0 * (-0.05f64).exp());
        assert_close("put_call_parity", parity, 0.0, 1e-8);
    }

    #[test]
    fn black_scholes_itm_matches_scipy() {
        let (price, delta) = black_scholes(120.0, 100.0, 1.0, 0.05, 0.2, true);
        assert_close("bs_itm_price", price, 26.169043946847296, 1e-10);
        assert_close("bs_itm_delta", delta, 0.8964550230770805, 1e-10);
    }

    // ── OU stationary variance ──────────────────────────────────────────

    #[test]
    fn ou_stationary_variance_matches() {
        let theta = 5.0;
        let sigma = 0.3;
        assert_close("ou_stat_var", ou_stationary_variance(sigma, theta), 0.009, 1e-15);
    }

    #[test]
    fn ou_autocorrelation_matches() {
        let theta = 5.0;
        assert_close("ou_acf_0.1", ou_autocorrelation(theta, 0.1), 0.6065306597126334, 1e-12);
        assert_close("ou_acf_0.5", ou_autocorrelation(theta, 0.5), 0.0820849986238988, 1e-12);
        assert_close("ou_acf_1.0", ou_autocorrelation(theta, 1.0), 0.006737946999085467, 1e-12);
    }

    // ── Poisson expected count ──────────────────────────────────────────

    #[test]
    fn poisson_expected_count_matches() {
        assert_close("poisson_E", poisson_expected_count(10.0, 5.0), 50.0, 1e-15);
    }

    // ── Quadratic variation of BM ───────────────────────────────────────

    #[test]
    fn brownian_quadratic_variation_converges_to_t() {
        // For Brownian motion on [0,1], QV should converge to 1.0 as n→∞
        let (_, path) = brownian_motion(1.0, 10000, 42);
        let qv = quadratic_variation(&path);
        // Statistical test: should be close to 1.0 (not exact due to finite steps)
        assert_close("qv_bm", qv, 1.0, 0.15);
    }

    // ── Markov chain stationary distribution ────────────────────────────

    #[test]
    fn markov_2state_stationary_matches() {
        // [[0.7, 0.3], [0.4, 0.6]] → π = [4/7, 3/7]
        let p = vec![0.7, 0.3, 0.4, 0.6];
        let pi = stationary_distribution(&p, 2);
        assert_close("pi[0]", pi[0], 4.0 / 7.0, 1e-8);
        assert_close("pi[1]", pi[1], 3.0 / 7.0, 1e-8);
    }

    #[test]
    fn markov_3state_stationary_sums_to_1() {
        let p = vec![0.5, 0.3, 0.2, 0.2, 0.5, 0.3, 0.1, 0.3, 0.6];
        let pi = stationary_distribution(&p, 3);
        let sum: f64 = pi.iter().sum();
        assert_close("pi_sum", sum, 1.0, 1e-8);
        // All positive
        for (i, &v) in pi.iter().enumerate() {
            assert!(v > 0.0, "pi[{}] = {} should be positive", i, v);
        }
    }

    // ── Brownian bridge endpoints ───────────────────────────────────────

    #[test]
    fn brownian_bridge_endpoints() {
        let bb = brownian_bridge(1.0, 2.0, 100, 42);
        assert_close("bb_start", bb[0], 0.0, 1e-12);
        assert_close("bb_end", bb[100], 2.0, 1e-10);
    }
}

// ===========================================================================
// 6. PHYSICS — verified against analytical solutions and NIST
// ===========================================================================

mod physics_parity {
    use super::*;
    use tambear::physics::*;

    // ── Physical constants ──────────────────────────────────────────────

    #[test]
    fn constants_match_nist() {
        assert_close("k_B", K_BOLTZMANN, 1.380649e-23, 1e-29);
        assert_close("hbar", H_BAR, 1.0545718e-34, 1e-40);
        assert_close("c", SPEED_OF_LIGHT, 2.99792458e8, 1.0);
        assert_close("G", G_GRAV, 6.67430e-11, 1e-15);
        assert_close("e", ELEM_CHARGE, 1.602176634e-19, 1e-28);
        assert_close("m_e", MASS_ELECTRON, 9.1093837015e-31, 1e-40);
        assert_close("a_0", BOHR_RADIUS, 5.29177210903e-11, 1e-20);
        assert_close("N_A", AVOGADRO, 6.02214076e23, 1e15);
        assert_close("R", GAS_CONSTANT, 8.314462618, 1e-8);
        assert_close("eps_0", EPSILON_0, 8.8541878128e-12, 1e-21);
    }

    // ── SHO exact solution ──────────────────────────────────────────────

    #[test]
    fn sho_exact_matches_analytical() {
        let omega = 2.0 * std::f64::consts::PI;
        let x0 = 1.0;
        let v0 = 0.0;

        // t=0: x=1, v=0
        let (x, v) = sho_exact(x0, v0, omega, 0.0);
        assert_close("sho_t0_x", x, 1.0, 1e-14);
        assert_close("sho_t0_v", v, 0.0, 1e-14);

        // t=0.25 (quarter period): x≈0, v=-omega
        let (x, v) = sho_exact(x0, v0, omega, 0.25);
        assert_close("sho_t025_x", x, 0.0, 1e-10);
        assert_close("sho_t025_v", v, -omega, 1e-10);

        // t=0.5 (half period): x=-1, v≈0
        let (x, v) = sho_exact(x0, v0, omega, 0.5);
        assert_close("sho_t05_x", x, -1.0, 1e-10);
        assert_close("sho_t05_v", v, 0.0, 1e-10);

        // t=1.0 (full period): x=1, v≈0
        let (x, v) = sho_exact(x0, v0, omega, 1.0);
        assert_close("sho_t1_x", x, 1.0, 1e-10);
        assert_close("sho_t1_v", v, 0.0, 1e-10);
    }

    // ── SHO energy conservation ─────────────────────────────────────────

    #[test]
    fn sho_energy_conserved() {
        let omega = 2.0 * std::f64::consts::PI;
        let mass = 1.0;
        let x0 = 1.0;
        let v0 = 0.0;
        let e0 = sho_energy(mass, omega, x0, v0);

        for &t in &[0.0, 0.1, 0.25, 0.5, 0.75, 1.0] {
            let (x, v) = sho_exact(x0, v0, omega, t);
            let e = sho_energy(mass, omega, x, v);
            assert_close(&format!("sho_E_t{}", t), e, e0, 1e-10);
        }
    }

    // ── Damped harmonic oscillator ──────────────────────────────────────

    #[test]
    fn dho_underdamped_matches_analytical() {
        let omega0 = 10.0;
        let gamma = 1.0;
        let x0 = 1.0;
        let v0 = 0.0;

        // t=0: x = x0
        let x = dho_underdamped(x0, v0, omega0, gamma, 0.0);
        assert_close("dho_t0", x, 1.0, 1e-14);

        // t=0.1: decaying oscillation
        let x = dho_underdamped(x0, v0, omega0, gamma, 0.1);
        let omega_d = (omega0 * omega0 - gamma * gamma).sqrt();
        let a = x0;
        let b = (v0 + gamma * x0) / omega_d;
        let expected = (-gamma * 0.1f64).exp() * (a * (omega_d * 0.1).cos() + b * (omega_d * 0.1).sin());
        assert_close("dho_t01", x, expected, 1e-12);

        // Large t: should decay toward 0
        let x_late = dho_underdamped(x0, v0, omega0, gamma, 5.0);
        assert!(x_late.abs() < 0.01, "dho at t=5 should be near 0, got {}", x_late);
    }

    // ── Kepler orbit ────────────────────────────────────────────────────

    #[test]
    fn kepler_circular_orbit() {
        let m_sun = 1.989e30;
        let r = 1.496e11; // 1 AU
        let v_circ = (G_GRAV * m_sun / r).sqrt();

        let orbit = kepler_orbit([r, 0.0, 0.0], [0.0, v_circ, 0.0], m_sun);
        // Eccentricity should be ~0 for circular orbit
        assert_close("kepler_e", orbit.eccentricity, 0.0, 1e-6);
        // Period should be ~1 year = ~3.156e7 seconds
        let year_seconds = 365.25 * 86400.0;
        assert_close("kepler_T", orbit.period, year_seconds, year_seconds * 0.01);
    }

    // ── Vis-viva ────────────────────────────────────────────────────────

    #[test]
    fn vis_viva_circular() {
        let m_sun = 1.989e30;
        let mu = G_GRAV * m_sun;
        let r = 1.496e11;
        let sma = r; // circular orbit: a = r
        let v = vis_viva(mu, r, sma);
        let v_circ = (mu / r).sqrt();
        assert_close("vis_viva", v, v_circ, 1e-3);
    }

    // ── Particle mechanics ──────────────────────────────────────────────

    #[test]
    fn kinetic_energy_and_momentum() {
        let p = Particle::new(1.0, [0.0, 0.0, 0.0], [10.0, 0.0, 0.0]);
        assert_close("KE", p.kinetic_energy(), 50.0, 1e-14);
        let mom = p.momentum();
        assert_close("px", mom[0], 10.0, 1e-14);
        assert_close("py", mom[1], 0.0, 1e-14);
    }

    // ── N-body energy conservation ──────────────────────────────────────

    #[test]
    fn nbody_energy_approximately_conserved() {
        let particles = vec![
            Particle::new(1e10, [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]),
            Particle::new(1.0, [1.0, 0.0, 0.0], [0.0, 0.001, 0.0]),
        ];
        let result = nbody_gravity(&particles, 0.01, 100);
        // Energy should be approximately conserved (Verlet is symplectic)
        let e0 = result.total_energy[0];
        let e_last = *result.total_energy.last().unwrap();
        let drift = ((e_last - e0) / e0.abs()).abs();
        assert!(drift < 0.01, "N-body energy drift = {:.2e}", drift);
    }
}

// ===========================================================================
// 7. FOLD IRREVERSIBILITY — verified against Python (bit-perfect)
// ===========================================================================

mod fold_irreversibility_parity {
    use super::*;
    use tambear::fold_irreversibility::*;

    // ── trailing_ones ───────────────────────────────────────────────────

    #[test]
    fn trailing_ones_matches_python() {
        assert_eq!(trailing_ones(0), 0);
        assert_eq!(trailing_ones(1), 1);   // ...001
        assert_eq!(trailing_ones(3), 2);   // ...011
        assert_eq!(trailing_ones(5), 1);   // ...101
        assert_eq!(trailing_ones(7), 3);   // ...0111
        assert_eq!(trailing_ones(6), 0);   // ...110
        assert_eq!(trailing_ones(15), 4);  // ...01111
        assert_eq!(trailing_ones(31), 5);  // 011111
        assert_eq!(trailing_ones(255), 8); // 11111111
        assert_eq!(trailing_ones(127), 7);
        assert_eq!(trailing_ones(13), 1);  // 1101
        assert_eq!(trailing_ones(11), 2);  // 1011
        assert_eq!(trailing_ones(10), 0);  // 1010
    }

    // ── collatz_odd_step ────────────────────────────────────────────────

    #[test]
    fn collatz_odd_step_matches_python() {
        // T(1) = (3+1)/4 = 1, v2=2
        assert_eq!(collatz_odd_step(1), (1, 2));
        // T(3) = 10/2 = 5, v2=1
        assert_eq!(collatz_odd_step(3), (5, 1));
        // T(5) = 16/16 = 1, v2=4
        assert_eq!(collatz_odd_step(5), (1, 4));
        // T(7) = 22/2 = 11, v2=1
        assert_eq!(collatz_odd_step(7), (11, 1));
        // T(27) = 82/2 = 41, v2=1
        assert_eq!(collatz_odd_step(27), (41, 1));
    }

    // ── temperature = trailing ones ─────────────────────────────────────

    #[test]
    fn temperature_is_trailing_ones() {
        for &n in &[1u128, 3, 5, 7, 9, 11, 13, 15, 27, 31, 63, 127] {
            assert_eq!(temperature(n), trailing_ones(n),
                "temperature({}) should equal trailing_ones({})", n, n);
        }
    }

    // ── trace_fold trajectory ───────────────────────────────────────────

    #[test]
    fn trace_fold_7_converges() {
        let traj = trace_fold(7, 1000);
        assert!(traj.converged, "Collatz from 7 should converge");
        assert_eq!(traj.initial_tau, 3); // 7 = ...0111
        assert_eq!(traj.steps[0].value, 7);
        assert_eq!(traj.steps.last().unwrap().value, 1);
    }

    #[test]
    fn trace_fold_27_converges() {
        let traj = trace_fold(27, 1000);
        assert!(traj.converged, "Collatz from 27 should converge");
        assert_eq!(traj.initial_tau, trailing_ones(27));
        // 27 has a long trajectory (>40 odd steps in the Collatz sequence)
        assert!(traj.steps.len() > 10, "27 should have > 10 odd steps, got {}", traj.steps.len());
    }

    // ── Extremal: 2^k - 1 (all-ones) ───────────────────────────────────

    #[test]
    fn extremal_all_ones_tau() {
        for k in 1..=10u32 {
            let n = (1u128 << k) - 1;
            assert_eq!(trailing_ones(n), k,
                "2^{}-1 = {} should have {} trailing ones", k, n, k);
        }
    }

    // ── Carry analysis ──────────────────────────────────────────────────

    #[test]
    fn carry_analysis_matches_python() {
        // For n=7: tau_in=3, 3*7+1=22, v2=1, next_odd=11, tau_out=2
        let (next, v2) = collatz_odd_step(7);
        assert_eq!(next, 11);
        assert_eq!(v2, 1);
        assert_eq!(trailing_ones(11), 2);

        // For n=15: tau_in=4, 3*15+1=46, v2=1, next_odd=23
        let (next, v2) = collatz_odd_step(15);
        assert_eq!(next, 23);
        assert_eq!(v2, 1);
    }

    // ── Fold sweep on small range ───────────────────────────────────────

    #[test]
    fn fold_sweep_small() {
        let result = fold_sweep(99, 1000);
        // All odd numbers 1..99 → 50 numbers
        assert_eq!(result.count, 50);
        // All should converge (verified for all n < 2^68)
        assert_close("convergence", result.convergence_rate, 1.0, 1e-10);
    }
}

// ===========================================================================
// 8. RNG — statistical verification of distribution moments
// ===========================================================================

mod rng_parity {
    use super::*;
    use tambear::rng::*;

    const N: usize = 100_000;
    const STAT_TOL: f64 = 0.05; // statistical tolerance for sample means

    // ── Student-t: mean=0, var=nu/(nu-2) ────────────────────────────────

    #[test]
    fn student_t_moments() {
        let mut rng = Xoshiro256::new(42);
        let nu = 5.0;
        let samples: Vec<f64> = (0..N).map(|_| sample_t(&mut rng, nu)).collect();
        let mean = samples.iter().sum::<f64>() / N as f64;
        let var = samples.iter().map(|x| (x - mean).powi(2)).sum::<f64>() / N as f64;
        let expected_var = nu / (nu - 2.0); // 5/3 = 1.667
        assert_close("t_mean", mean, 0.0, 0.1);
        assert_close("t_var", var, expected_var, 0.3);
    }

    // ── Chi-squared: mean=k, var=2k ─────────────────────────────────────

    #[test]
    fn chi2_moments() {
        let mut rng = Xoshiro256::new(42);
        let k = 5.0;
        let samples: Vec<f64> = (0..N).map(|_| sample_chi2(&mut rng, k)).collect();
        let mean = samples.iter().sum::<f64>() / N as f64;
        let var = samples.iter().map(|x| (x - mean).powi(2)).sum::<f64>() / N as f64;
        assert_close("chi2_mean", mean, k, 0.1);
        assert_close("chi2_var", var, 2.0 * k, 0.5);
    }

    // ── F distribution: mean=d2/(d2-2) ──────────────────────────────────

    #[test]
    fn f_distribution_mean() {
        let mut rng = Xoshiro256::new(42);
        let d1 = 5.0;
        let d2 = 10.0;
        let samples: Vec<f64> = (0..N).map(|_| sample_f(&mut rng, d1, d2)).collect();
        let mean = samples.iter().sum::<f64>() / N as f64;
        let expected_mean = d2 / (d2 - 2.0); // 10/8 = 1.25
        assert_close("f_mean", mean, expected_mean, 0.1);
    }

    // ── Cauchy: median = x0 ─────────────────────────────────────────────

    #[test]
    fn cauchy_median_matches() {
        let mut rng = Xoshiro256::new(42);
        let x0 = 3.0;
        let gamma = 1.0;
        let mut samples: Vec<f64> = (0..N).map(|_| sample_cauchy(&mut rng, x0, gamma)).collect();
        samples.sort_by(|a, b| a.total_cmp(b));
        let median = samples[N / 2];
        assert_close("cauchy_median", median, x0, 0.1);
    }

    // ── Lognormal: E[X] = exp(mu + sigma^2/2) ──────────────────────────

    #[test]
    fn lognormal_mean() {
        let mut rng = Xoshiro256::new(42);
        let mu = 0.0;
        let sigma = 1.0;
        let samples: Vec<f64> = (0..N).map(|_| sample_lognormal(&mut rng, mu, sigma)).collect();
        let mean = samples.iter().sum::<f64>() / N as f64;
        let expected_mean = (mu + sigma * sigma / 2.0).exp(); // e^0.5 ≈ 1.6487
        assert_close("lognormal_mean", mean, expected_mean, 0.1);
    }

    // ── Geometric: E[X] = (1-p)/p ───────────────────────────────────────

    #[test]
    fn geometric_mean_matches() {
        let mut rng = Xoshiro256::new(42);
        let p = 0.3;
        let samples: Vec<u64> = (0..N).map(|_| sample_geometric(&mut rng, p)).collect();
        let mean = samples.iter().sum::<u64>() as f64 / N as f64;
        let expected = (1.0 - p) / p; // 0.7/0.3 ≈ 2.333
        assert_close("geometric_mean", mean, expected, 0.15);
    }

    // ── Bernoulli: E[X] = p ─────────────────────────────────────────────

    #[test]
    fn bernoulli_frequency() {
        let mut rng = Xoshiro256::new(42);
        let p = 0.7;
        let count = (0..N).filter(|_| sample_bernoulli(&mut rng, p)).count();
        let freq = count as f64 / N as f64;
        assert_close("bernoulli_p", freq, p, 0.02);
    }

    // ── Uniform: all values in [0,1) ────────────────────────────────────

    #[test]
    fn uniform_range_and_mean() {
        let mut rng = Xoshiro256::new(42);
        let samples: Vec<f64> = (0..N).map(|_| rng.next_f64()).collect();
        let mean = samples.iter().sum::<f64>() / N as f64;
        assert_close("uniform_mean", mean, 0.5, 0.01);
        assert!(samples.iter().all(|&x| x >= 0.0 && x < 1.0));
    }

    // ── Exponential: E[X] = 1/lambda, all positive ──────────────────────

    #[test]
    fn exponential_mean_and_positivity() {
        let mut rng = Xoshiro256::new(42);
        let lambda = 3.0;
        let samples: Vec<f64> = (0..N).map(|_| sample_exponential(&mut rng, lambda)).collect();
        let mean = samples.iter().sum::<f64>() / N as f64;
        assert_close("exp_mean", mean, 1.0 / lambda, STAT_TOL);
        assert!(samples.iter().all(|&x| x >= 0.0));
    }

    // ── Gamma(alpha, beta): E[X] = alpha/beta ───────────────────────────

    #[test]
    fn gamma_mean_matches_theory() {
        let mut rng = Xoshiro256::new(42);
        let alpha = 2.0;
        let beta = 1.0;
        let samples: Vec<f64> = (0..N).map(|_| sample_gamma(&mut rng, alpha, beta)).collect();
        let mean = samples.iter().sum::<f64>() / N as f64;
        assert_close("gamma_mean", mean, alpha / beta, STAT_TOL * 2.0);
    }

    // ── Beta(a,b): E[X] = a/(a+b) ──────────────────────────────────────

    #[test]
    fn beta_mean_matches_theory() {
        let mut rng = Xoshiro256::new(42);
        let a = 2.0;
        let b = 5.0;
        let samples: Vec<f64> = (0..N).map(|_| sample_beta(&mut rng, a, b)).collect();
        let mean = samples.iter().sum::<f64>() / N as f64;
        let expected = a / (a + b);
        assert_close("beta_mean", mean, expected, STAT_TOL);
    }
}
