//! Scan kernel generation engine.
//!
//! Takes an AssociativeOp and generates CUDA source for a parallel scan kernel.
//! Two variants:
//! - `generate_scan_kernel`: single-block scan (testing, small arrays)
//! - `generate_multiblock_scan`: three-phase multi-block scan (production)
//!
//! Both use Blelloch-style work-efficient prefix scan:
//! up-sweep (reduce) + down-sweep (distribute), O(n) work, O(log n) depth.

use crate::ops::AssociativeOp;

/// Generate CUDA source for an inclusive prefix scan kernel with the given operator.
///
/// The generated kernel:
/// 1. Lifts each input element into the operator's state space
/// 2. Performs Blelloch up-sweep (pairwise combine)
/// 3. Performs down-sweep (distribute partial results)
/// 4. Extracts output from final state
///
/// The operator's `cuda_combine` expression MUST be associative for correctness.
/// This is the liftability test: associativity enables O(log n) parallel depth.
pub fn generate_scan_kernel(op: &dyn AssociativeOp) -> String {
    let state_type = op.cuda_state_type();
    let identity = op.cuda_identity();
    let lift_body = op.cuda_lift_body();
    let combine_body = op.cuda_combine_body();
    let extract = op.cuda_extract();

    // Determine if state is a struct or scalar
    let is_struct = state_type.contains("struct");
    let type_decl = if is_struct {
        format!("{};\ntypedef {} state_t;",
            state_type,
            // Extract struct name
            state_type.split_whitespace().nth(1).unwrap_or("State")
                .trim_end_matches('{').trim())
    } else {
        format!("typedef {} state_t;", state_type)
    };

    format!(
        r#"// Auto-generated scan kernel for operator: {op_name}
// Liftability: associative operator -> O(log n) parallel scan
// Generated by winrapids-scan (Rust)

{type_decl}

__device__ __forceinline__ state_t make_identity() {{
    state_t id = {identity};
    return id;
}}

__device__ __forceinline__ state_t lift_element(double x) {{
{lift_body}
}}

__device__ __forceinline__ state_t combine_states(state_t a, state_t b) {{
{combine_body}
}}

__device__ __forceinline__ double extract_primary(state_t s) {{
    return {extract};
}}

// Inclusive scan: each block processes blockDim.x elements.
// Shared memory stores state_t per thread.
extern "C" __global__ void scan_inclusive(
    const double* __restrict__ input,
    double* __restrict__ output,
    int n
) {{
    extern __shared__ char shared_raw[];
    state_t* shared = (state_t*)shared_raw;

    int tid = threadIdx.x;
    int gid = blockIdx.x * blockDim.x + tid;

    // Load: lift each element into state space
    shared[tid] = (gid < n) ? lift_element(input[gid]) : make_identity();
    __syncthreads();

    // Up-sweep (reduce phase)
    for (int stride = 1; stride < blockDim.x; stride *= 2) {{
        int idx = (tid + 1) * stride * 2 - 1;
        if (idx < blockDim.x) {{
            shared[idx] = combine_states(shared[idx - stride], shared[idx]);
        }}
        __syncthreads();
    }}

    // Down-sweep (distribute phase)
    for (int stride = blockDim.x / 4; stride > 0; stride /= 2) {{
        int idx = (tid + 1) * stride * 2 - 1;
        if (idx + stride < blockDim.x) {{
            shared[idx + stride] = combine_states(shared[idx], shared[idx + stride]);
        }}
        __syncthreads();
    }}

    // Extract and write output
    if (gid < n) {{
        output[gid] = extract_primary(shared[tid]);
    }}
}}
"#,
        op_name = op.name(),
        type_decl = type_decl,
        identity = identity,
        lift_body = lift_body,
        combine_body = combine_body,
        extract = extract,
    )
}

/// Generate CUDA source for a multi-block parallel scan.
///
/// Produces three kernels in one source:
/// 1. `scan_per_block` — per-block inclusive scan, writes state buffer + block totals
/// 2. `scan_block_totals` — single-block scan of block totals
/// 3. `propagate_extract` — propagate block prefixes and extract outputs
///
/// The state buffer stores full `state_t` values (not extracted doubles) so that
/// propagation works correctly for complex operators like WelfordOp.
///
/// Supports up to BLOCK_SIZE × 1024 elements (1M with BLOCK_SIZE=1024).
pub fn generate_multiblock_scan(op: &dyn AssociativeOp) -> String {
    let state_type = op.cuda_state_type();
    let identity = op.cuda_identity();
    let lift_body = op.cuda_lift_body();
    let combine_body = op.cuda_combine_body();
    let extract = op.cuda_extract();
    let secondaries = op.cuda_extract_secondary();

    let is_struct = state_type.contains("struct");
    let type_decl = if is_struct {
        format!("{};\ntypedef {} state_t;",
            state_type,
            state_type.split_whitespace().nth(1).unwrap_or("State")
                .trim_end_matches('{').trim())
    } else {
        format!("typedef {} state_t;", state_type)
    };

    // Secondary extract functions
    let mut secondary_funcs = String::new();
    for (i, expr) in secondaries.iter().enumerate() {
        secondary_funcs += &format!(
            "\n__device__ __forceinline__ double extract_secondary_{i}(state_t s) {{\n    return {expr};\n}}\n"
        );
    }

    // Output writes in propagate_extract
    let mut output_writes = String::from("        out0[gid] = extract_primary(s);\n");
    for i in 0..secondaries.len() {
        output_writes += &format!("        out{k}[gid] = extract_secondary_{i}(s);\n", k = i + 1);
    }

    // Output parameters for propagate_extract (fixed: always out0 + out1)
    // out1 is a dummy pointer for single-output ops (never written)
    let output_params = "    double* __restrict__ out0,\n    double* __restrict__ out1";

    format!(
        r#"// Multi-block parallel scan for operator: {op_name}
// Three-phase: scan_per_block -> scan_block_totals -> propagate_extract
// Generated by winrapids-scan (Rust)

{type_decl}

__device__ __forceinline__ state_t make_identity() {{
    state_t id = {identity};
    return id;
}}

__device__ __forceinline__ state_t lift_element(double x) {{
{lift_body}
}}

__device__ __forceinline__ state_t combine_states(state_t a, state_t b) {{
{combine_body}
}}

__device__ __forceinline__ double extract_primary(state_t s) {{
    return {extract};
}}
{secondary_funcs}

// Phase 1: Per-block inclusive scan.
// Writes full state_t to state_out (for correct propagation of complex operators).
// Writes block total to block_totals[blockIdx.x].
extern "C" __global__ void scan_per_block(
    const double* __restrict__ input,
    state_t* __restrict__ state_out,
    state_t* __restrict__ block_totals,
    int n
) {{
    extern __shared__ char shared_raw[];
    state_t* shared = (state_t*)shared_raw;

    int tid = threadIdx.x;
    int gid = blockIdx.x * blockDim.x + tid;

    shared[tid] = (gid < n) ? lift_element(input[gid]) : make_identity();
    __syncthreads();

    // Up-sweep (reduce)
    for (int stride = 1; stride < blockDim.x; stride *= 2) {{
        int idx = (tid + 1) * stride * 2 - 1;
        if (idx < blockDim.x) {{
            shared[idx] = combine_states(shared[idx - stride], shared[idx]);
        }}
        __syncthreads();
    }}

    // Down-sweep (distribute)
    for (int stride = blockDim.x / 4; stride > 0; stride /= 2) {{
        int idx = (tid + 1) * stride * 2 - 1;
        if (idx + stride < blockDim.x) {{
            shared[idx + stride] = combine_states(shared[idx], shared[idx + stride]);
        }}
        __syncthreads();
    }}

    if (gid < n) state_out[gid] = shared[tid];
    // Last thread in block writes the block total
    if (tid == blockDim.x - 1) block_totals[blockIdx.x] = shared[tid];
}}

// Phase 2: Single-block scan of block totals.
// After this, block_totals[i] = inclusive prefix of block totals 0..i.
extern "C" __global__ void scan_block_totals(
    state_t* __restrict__ totals,
    int n_blocks
) {{
    extern __shared__ char shared_raw[];
    state_t* shared = (state_t*)shared_raw;

    int tid = threadIdx.x;
    shared[tid] = (tid < n_blocks) ? totals[tid] : make_identity();
    __syncthreads();

    for (int stride = 1; stride < blockDim.x; stride *= 2) {{
        int idx = (tid + 1) * stride * 2 - 1;
        if (idx < blockDim.x) {{
            shared[idx] = combine_states(shared[idx - stride], shared[idx]);
        }}
        __syncthreads();
    }}

    for (int stride = blockDim.x / 4; stride > 0; stride /= 2) {{
        int idx = (tid + 1) * stride * 2 - 1;
        if (idx + stride < blockDim.x) {{
            shared[idx + stride] = combine_states(shared[idx], shared[idx + stride]);
        }}
        __syncthreads();
    }}

    if (tid < n_blocks) totals[tid] = shared[tid];
}}

// Phase 3: Propagate block prefixes and extract output(s).
// For block i > 0, combine block_prefixes[i-1] with each element's state.
extern "C" __global__ void propagate_extract(
{output_params},
    const state_t* __restrict__ state_in,
    const state_t* __restrict__ block_prefixes,
    int n
) {{
    int gid = blockIdx.x * blockDim.x + threadIdx.x;
    if (gid < n) {{
        state_t s = state_in[gid];
        if (blockIdx.x > 0) {{
            s = combine_states(block_prefixes[blockIdx.x - 1], s);
        }}
{output_writes}    }}
}}

// sizeof validation: returns sizeof(state_t) so Rust can verify
// that its state_byte_size() matches the actual CUDA struct layout.
// Run once per operator at module load time. Mismatch = silent memory
// corruption in shared memory scan, so we panic before any data touches
// the kernel.
extern "C" __global__ void query_sizeof(int* __restrict__ result) {{
    result[0] = (int)sizeof(state_t);
}}
"#,
        op_name = op.name(),
        type_decl = type_decl,
        identity = identity,
        lift_body = lift_body,
        combine_body = combine_body,
        extract = extract,
        secondary_funcs = secondary_funcs,
        output_params = output_params,
        output_writes = output_writes,
    )
}
