//! Scan kernel generation engine.
//!
//! Takes an AssociativeOp and generates CUDA source for a parallel scan kernel.
//! The generated kernel uses Blelloch-style work-efficient prefix scan:
//! up-sweep (reduce) + down-sweep (distribute), O(n) work, O(log n) depth.
//!
//! GPU launch integration via cudarc is in a separate `launch` module
//! (to be built once the kernel source is validated).

use crate::ops::AssociativeOp;

/// Generate CUDA source for an inclusive prefix scan kernel with the given operator.
///
/// The generated kernel:
/// 1. Lifts each input element into the operator's state space
/// 2. Performs Blelloch up-sweep (pairwise combine)
/// 3. Performs down-sweep (distribute partial results)
/// 4. Extracts output from final state
///
/// The operator's `cuda_combine` expression MUST be associative for correctness.
/// This is the liftability test: associativity enables O(log n) parallel depth.
pub fn generate_scan_kernel(op: &dyn AssociativeOp) -> String {
    let state_type = op.cuda_state_type();
    let identity = op.cuda_identity();
    let combine = op.cuda_combine();
    let lift = op.cuda_lift_element();
    let extract = op.cuda_extract();

    // Determine if state is a struct or scalar
    let is_struct = state_type.contains("struct");
    let type_decl = if is_struct {
        format!("{};\ntypedef {} state_t;",
            state_type,
            // Extract struct name
            state_type.split_whitespace().nth(1).unwrap_or("State")
                .trim_end_matches('{').trim())
    } else {
        format!("typedef {} state_t;", state_type)
    };

    format!(
        r#"// Auto-generated scan kernel for operator: {op_name}
// Liftability: associative operator -> O(log n) parallel scan
// Generated by winrapids-scan (Rust)

{type_decl}

__device__ __forceinline__ state_t make_identity() {{
    state_t id = {identity};
    return id;
}}

__device__ __forceinline__ state_t lift_element(double x) {{
    state_t s = {lift};
    return s;
}}

__device__ __forceinline__ state_t combine_states(state_t a, state_t b) {{
    state_t result = {combine};
    return result;
}}

__device__ __forceinline__ double extract_primary(state_t s) {{
    return {extract};
}}

// Inclusive scan: each block processes blockDim.x elements.
// Shared memory stores state_t per thread.
extern "C" __global__ void scan_inclusive(
    const double* __restrict__ input,
    double* __restrict__ output,
    int n
) {{
    extern __shared__ char shared_raw[];
    state_t* shared = (state_t*)shared_raw;

    int tid = threadIdx.x;
    int gid = blockIdx.x * blockDim.x + tid;

    // Load: lift each element into state space
    shared[tid] = (gid < n) ? lift_element(input[gid]) : make_identity();
    __syncthreads();

    // Up-sweep (reduce phase)
    for (int stride = 1; stride < blockDim.x; stride *= 2) {{
        int idx = (tid + 1) * stride * 2 - 1;
        if (idx < blockDim.x) {{
            shared[idx] = combine_states(shared[idx - stride], shared[idx]);
        }}
        __syncthreads();
    }}

    // Down-sweep (distribute phase)
    for (int stride = blockDim.x / 4; stride > 0; stride /= 2) {{
        int idx = (tid + 1) * stride * 2 - 1;
        if (idx + stride < blockDim.x) {{
            shared[idx + stride] = combine_states(shared[idx], shared[idx + stride]);
        }}
        __syncthreads();
    }}

    // Extract and write output
    if (gid < n) {{
        output[gid] = extract_primary(shared[tid]);
    }}
}}
"#,
        op_name = op.name(),
        type_decl = type_decl,
        identity = identity,
        lift = lift,
        combine = combine,
        extract = extract,
    )
}
