//! Tiled accumulation kernel generation engine.
//!
//! Takes a TiledOp and generates CUDA source for a tiled matmul-like kernel.
//! The generated kernel:
//!   1. Tiles A (M×K) and B (K×N) into TILE_M × TILE_K and TILE_K × TILE_N blocks
//!   2. Each thread block computes one output tile of C (TILE_M × TILE_N)
//!   3. Tiles of A and B are loaded into shared memory
//!   4. Pre-transforms are applied on load (fused centering/normalization)
//!   5. Accumulation happens in registers (one acc per output element per thread)
//!   6. Extract converts accumulators to output values
//!
//! The pre-transform fusion is the key advantage over cuBLASLt for data science:
//! cuBLASLt would materialize centered/normalized intermediates before the GEMM.
//! This kernel reads raw data once and transforms on the fly.

use crate::ops::TiledOp;

/// Tile dimensions. TILE_M × TILE_N output per block, accumulated over TILE_K strips.
const TILE_M: usize = 16;
const TILE_N: usize = 16;
const TILE_K: usize = 16;

/// Generate CUDA source for a tiled accumulation kernel.
///
/// The kernel computes C[i,j] = extract(accumulate(A[i,:], B[:,j]))
/// where the accumulation is defined by the TiledOp.
///
/// Shape: A is M×K, B is K×N, C is M×N.
pub fn generate_tiled_kernel(op: &dyn TiledOp) -> String {
    let acc_type = op.cuda_acc_type();
    let identity = op.cuda_identity();
    let accumulate = op.cuda_accumulate_body();
    let extract = op.cuda_extract();
    let pre_a = op.cuda_pre_transform_a();
    let pre_b = op.cuda_pre_transform_b();

    let is_struct = acc_type.contains("struct");
    let type_decl = if is_struct {
        format!("{};\ntypedef {} acc_t;",
            acc_type,
            acc_type.split_whitespace().nth(1).unwrap_or("Acc")
                .trim_end_matches('{').trim())
    } else {
        format!("typedef {} acc_t;", acc_type)
    };

    // Pre-transform functions
    let pre_a_fn = if pre_a == "x" {
        "__device__ __forceinline__ double pre_transform_a(double x) { return x; }".into()
    } else {
        format!("__device__ __forceinline__ double pre_transform_a(double x) {{ return {}; }}", pre_a)
    };
    let pre_b_fn = if pre_b == "x" {
        "__device__ __forceinline__ double pre_transform_b(double x) { return x; }".into()
    } else {
        format!("__device__ __forceinline__ double pre_transform_b(double x) {{ return {}; }}", pre_b)
    };

    format!(
        r#"// Tiled accumulation kernel for operator: {op_name}
// TILE_M={tile_m}, TILE_N={tile_n}, TILE_K={tile_k}
// Generated by winrapids-tiled (Rust)

{type_decl}

__device__ __forceinline__ acc_t make_identity() {{
    acc_t acc = {identity};
    return acc;
}}

{pre_a_fn}
{pre_b_fn}

// Tiled kernel: C[M,N] = op.extract(op.accumulate(A[M,K], B[K,N]))
// Each thread block handles one TILE_M x TILE_N output tile.
// Threads within a block cooperatively load A/B tiles into shared memory.
extern "C" __global__ void tiled_accumulate(
    const double* __restrict__ A,
    const double* __restrict__ B,
    double* __restrict__ C,
    int M, int N, int K
) {{
    // Block computes C[by*TILE_M .. (by+1)*TILE_M, bx*TILE_N .. (bx+1)*TILE_N]
    int bx = blockIdx.x;
    int by = blockIdx.y;
    int tx = threadIdx.x;  // 0..TILE_N-1
    int ty = threadIdx.y;  // 0..TILE_M-1

    int row = by * {tile_m} + ty;
    int col = bx * {tile_n} + tx;

    __shared__ double As[{tile_m}][{tile_k}];
    __shared__ double Bs[{tile_k}][{tile_n}];

    acc_t acc = make_identity();

    // Walk over K dimension in tiles
    for (int t = 0; t < (K + {tile_k} - 1) / {tile_k}; t++) {{
        // Cooperative load of A tile
        int a_col = t * {tile_k} + tx;
        if (row < M && a_col < K) {{
            As[ty][tx] = pre_transform_a(A[row * K + a_col]);
        }} else {{
            As[ty][tx] = 0.0;
        }}

        // Cooperative load of B tile
        int b_row = t * {tile_k} + ty;
        if (b_row < K && col < N) {{
            Bs[ty][tx] = pre_transform_b(B[b_row * N + col]);
        }} else {{
            Bs[ty][tx] = 0.0;
        }}

        __syncthreads();

        // Accumulate over the K tile
        for (int k = 0; k < {tile_k}; k++) {{
            double a_val = As[ty][k];
            double b_val = Bs[k][tx];
{accumulate}
        }}

        __syncthreads();
    }}

    // Extract and write output
    if (row < M && col < N) {{
        C[row * N + col] = {extract};
    }}
}}
"#,
        op_name = op.name(),
        type_decl = type_decl,
        identity = identity,
        pre_a_fn = pre_a_fn,
        pre_b_fn = pre_b_fn,
        accumulate = accumulate,
        extract = extract,
        tile_m = TILE_M,
        tile_n = TILE_N,
        tile_k = TILE_K,
    )
}
