//! Tiled accumulation kernel generation engine.
//!
//! Takes a TiledOp and generates CUDA source for a tiled matmul-like kernel.
//! The generated kernel:
//!   1. Tiles A (M×K) and B (K×N) into TILE_M × TILE_K and TILE_K × TILE_N blocks
//!   2. Each thread block computes one output tile of C (TILE_M × TILE_N)
//!   3. Tiles of A and B are loaded into shared memory
//!   4. Pre-transforms are applied on load (fused centering/normalization)
//!   5. Accumulation happens in registers (one acc per output element per thread)
//!   6. Extract converts accumulators to output values
//!
//! The pre-transform fusion is the key advantage over cuBLASLt for data science:
//! cuBLASLt would materialize centered/normalized intermediates before the GEMM.
//! This kernel reads raw data once and transforms on the fly.

use crate::ops::TiledOp;

/// Tile dimensions. TILE_M × TILE_N output per block, accumulated over TILE_K strips.
const TILE_M: usize = 16;
const TILE_N: usize = 16;
const TILE_K: usize = 16;

/// Generate WGSL compute source for a tiled accumulation kernel.
///
/// Equivalent to [`generate_tiled_kernel`] but emits WGSL instead of CUDA C.
/// Uses `f32` throughout (WGSL does not natively support `f64`).
///
/// The generated kernel has the same logical structure:
/// - A: M×K storage buffer (read-only, f32)
/// - B: K×N storage buffer (read-only, f32)
/// - C: M×N storage buffer (read-write, f32)
/// - dims: [M, N, K] as array<i32, 4> (i32 to match TiledEngine's upload convention)
///
/// Entry point: `tiled_accumulate`.
pub fn generate_tiled_kernel_wgsl(op: &dyn TiledOp) -> String {
    let acc_type  = op.wgsl_acc_type();
    let identity  = op.wgsl_identity();
    let accumulate = op.wgsl_accumulate_body();
    let extract   = op.wgsl_extract();
    let pre_a     = op.cuda_pre_transform_a();
    let pre_b     = op.cuda_pre_transform_b();

    let tile_m = TILE_M;
    let tile_n = TILE_N;
    let tile_k = TILE_K;

    // WGSL pre-transform functions (f32 equivalent)
    let pre_a_fn = if pre_a == "x" {
        "fn pre_transform_a(x: f32) -> f32 { return x; }".to_owned()
    } else {
        // Basic translation: `x` in CUDA maps to x in WGSL
        format!("fn pre_transform_a(x: f32) -> f32 {{ return f32({}); }}", pre_a)
    };
    let pre_b_fn = if pre_b == "x" {
        "fn pre_transform_b(x: f32) -> f32 { return x; }".to_owned()
    } else {
        format!("fn pre_transform_b(x: f32) -> f32 {{ return f32({}); }}", pre_b)
    };

    let params_key = op.params_key();

    format!(
        r#"// WGSL tiled accumulation kernel for operator: {op_name}
// params: {params_key}
// TILE_M={tile_m}, TILE_N={tile_n}, TILE_K={tile_k}
// f32 precision (WGSL constraint — f64 not natively supported)
// Generated by winrapids-tiled (Rust)

@group(0) @binding(0) var<storage, read>       A: array<f32>;
@group(0) @binding(1) var<storage, read>       B: array<f32>;
@group(0) @binding(2) var<storage, read_write> C: array<f32>;
@group(0) @binding(3) var<storage, read>       dims: array<i32>;

var<workgroup> As: array<f32, {tile_mk}>;  // {tile_m}×{tile_k}
var<workgroup> Bs: array<f32, {tile_kn}>;  // {tile_k}×{tile_n}

{pre_a_fn}
{pre_b_fn}

@compute @workgroup_size({tile_n}, {tile_m})
fn tiled_accumulate(
    @builtin(global_invocation_id) gid:  vec3<u32>,
    @builtin(local_invocation_id)  lid:  vec3<u32>,
    @builtin(workgroup_id)         wid:  vec3<u32>,
) {{
    let M = u32(dims[0]);
    let N = u32(dims[1]);
    let K = u32(dims[2]);

    let tx  = lid.x;
    let ty  = lid.y;
    let row = wid.y * {tile_m}u + ty;
    let col = wid.x * {tile_n}u + tx;

    var acc: {acc_type} = {identity};

    // Walk over K dimension in tiles of size {tile_k}
    var t: u32 = 0u;
    loop {{
        if t >= (K + {tile_km1}u) / {tile_k}u {{ break; }}

        // Cooperative load of A tile: A[row, t*TILE_K + tx]
        let a_col = t * {tile_k}u + tx;
        if row < M && a_col < K {{
            As[ty * {tile_k}u + tx] = pre_transform_a(A[row * K + a_col]);
        }} else {{
            As[ty * {tile_k}u + tx] = 0.0;
        }}

        // Cooperative load of B tile: B[t*TILE_K + ty, col]
        let b_row = t * {tile_k}u + ty;
        if b_row < K && col < N {{
            Bs[ty * {tile_n}u + tx] = pre_transform_b(B[b_row * N + col]);
        }} else {{
            Bs[ty * {tile_n}u + tx] = 0.0;
        }}

        workgroupBarrier();

        // Accumulate over the K tile
        var k: u32 = 0u;
        loop {{
            if k >= {tile_k}u {{ break; }}
            let a_val = As[ty * {tile_k}u + k];
            let b_val = Bs[k  * {tile_n}u + tx];
{accumulate}
            k += 1u;
        }}

        workgroupBarrier();
        t += 1u;
    }}

    // Extract and write output
    if row < M && col < N {{
        C[row * N + col] = {extract};
    }}
}}
"#,
        op_name    = op.name(),
        params_key = params_key,
        acc_type   = acc_type,
        identity   = identity,
        pre_a_fn   = pre_a_fn,
        pre_b_fn   = pre_b_fn,
        accumulate = accumulate,
        extract    = extract,
        tile_m     = tile_m,
        tile_n     = tile_n,
        tile_k     = tile_k,
        tile_mk    = tile_m * tile_k,
        tile_kn    = tile_k * tile_n,
        tile_km1   = tile_k - 1,
    )
}

/// Generate CUDA source for a tiled accumulation kernel.
///
/// The kernel computes C[i,j] = extract(accumulate(A[i,:], B[:,j]))
/// where the accumulation is defined by the TiledOp.
///
/// Shape: A is M×K, B is K×N, C is M×N.
///
/// `use_f32`: if true, uses `float` instead of `double` for data arrays and
/// pre-transform functions. Accumulator type is controlled by the TiledOp
/// (struct accumulators like SufficientStats keep their own types).
pub fn generate_tiled_kernel(op: &dyn TiledOp) -> String {
    generate_tiled_kernel_precision(op, false)
}

/// Generate CUDA tiled kernel with explicit precision control.
pub fn generate_tiled_kernel_precision(op: &dyn TiledOp, use_f32: bool) -> String {
    let t = if use_f32 { "float" } else { "double" };
    let acc_type = op.cuda_acc_type();
    let identity = op.cuda_identity();
    let accumulate = op.cuda_accumulate_body();
    let extract = op.cuda_extract();
    let pre_a = op.cuda_pre_transform_a();
    let pre_b = op.cuda_pre_transform_b();

    let is_struct = acc_type.contains("struct");
    let type_decl = if is_struct {
        format!("{};\ntypedef {} acc_t;",
            acc_type,
            acc_type.split_whitespace().nth(1).unwrap_or("Acc")
                .trim_end_matches('{').trim())
    } else {
        format!("typedef {} acc_t;", acc_type)
    };

    // Pre-transform functions
    let pre_a_fn = if pre_a == "x" {
        format!("__device__ __forceinline__ {} pre_transform_a({} x) {{ return x; }}", t, t)
    } else {
        format!("__device__ __forceinline__ {} pre_transform_a({} x) {{ return {}; }}", t, t, pre_a)
    };
    let pre_b_fn = if pre_b == "x" {
        format!("__device__ __forceinline__ {} pre_transform_b({} x) {{ return x; }}", t, t)
    } else {
        format!("__device__ __forceinline__ {} pre_transform_b({} x) {{ return {}; }}", t, t, pre_b)
    };

    let params_key = op.params_key();

    format!(
        r#"// Tiled accumulation kernel for operator: {op_name}
// params: {params_key}
// TILE_M={tile_m}, TILE_N={tile_n}, TILE_K={tile_k}
// precision: {t}
// Generated by winrapids-tiled (Rust)

{type_decl}

__device__ __forceinline__ acc_t make_identity() {{
    acc_t acc = {identity};
    return acc;
}}

{pre_a_fn}
{pre_b_fn}

// Tiled kernel: C[M,N] = op.extract(op.accumulate(A[M,K], B[K,N]))
// Each thread block handles one TILE_M x TILE_N output tile.
// Threads within a block cooperatively load A/B tiles into shared memory.
extern "C" __global__ void tiled_accumulate(
    const {t}* __restrict__ A,
    const {t}* __restrict__ B,
    {t}* __restrict__ C,
    const int* __restrict__ dims
) {{
    int M = dims[0]; int N = dims[1]; int K = dims[2];
    // Block computes C[by*TILE_M .. (by+1)*TILE_M, bx*TILE_N .. (bx+1)*TILE_N]
    int bx = blockIdx.x;
    int by = blockIdx.y;
    int tx = threadIdx.x;  // 0..TILE_N-1
    int ty = threadIdx.y;  // 0..TILE_M-1

    int row = by * {tile_m} + ty;
    int col = bx * {tile_n} + tx;

    __shared__ {t} As[{tile_m}][{tile_k}];
    __shared__ {t} Bs[{tile_k}][{tile_n}];

    acc_t acc = make_identity();

    // Walk over K dimension in tiles
    for (int t = 0; t < (K + {tile_k} - 1) / {tile_k}; t++) {{
        // Cooperative load of A tile
        int a_col = t * {tile_k} + tx;
        if (row < M && a_col < K) {{
            As[ty][tx] = pre_transform_a(A[row * K + a_col]);
        }} else {{
            As[ty][tx] = 0.0;
        }}

        // Cooperative load of B tile
        int b_row = t * {tile_k} + ty;
        if (b_row < K && col < N) {{
            Bs[ty][tx] = pre_transform_b(B[b_row * N + col]);
        }} else {{
            Bs[ty][tx] = 0.0;
        }}

        __syncthreads();

        // Accumulate over the K tile
        for (int k = 0; k < {tile_k}; k++) {{
            {t} a_val = As[ty][k];
            {t} b_val = Bs[k][tx];
{accumulate}
        }}

        __syncthreads();
    }}

    // Extract and write output
    if (row < M && col < N) {{
        C[row * N + col] = {extract};
    }}
}}
"#,
        op_name    = op.name(),
        params_key = params_key,
        type_decl  = type_decl,
        identity   = identity,
        pre_a_fn   = pre_a_fn,
        pre_b_fn   = pre_b_fn,
        accumulate = accumulate,
        extract    = extract,
        t          = t,
        tile_m     = TILE_M,
        tile_n     = TILE_N,
        tile_k     = TILE_K,
    )
}
