//! Local context kernel generation engine.
//!
//! Generates a single CUDA kernel that:
//! 1. Gathers values at all fixed offsets (one coalesced read per offset)
//! 2. Computes all requested features from the gathered neighborhood
//! 3. Writes all feature outputs (one coalesced write per feature)
//!
//! One kernel, one read of the input, all features for all positions.
//! Replaces N separate shift/diff/rolling/peak kernels.

use crate::ops::LocalContextSpec;

/// Generate CUDA source for a local context kernel.
///
/// The kernel processes one element per thread. Each thread:
/// - Reads the center value data[gid]
/// - Gathers all offset values into registers
/// - Computes all requested features
/// - Writes outputs to N separate output arrays
pub fn generate_local_context_kernel(spec: &LocalContextSpec) -> String {
    let n_offsets = spec.offsets.len();
    let n_outputs = spec.output_width();

    // Generate offset array as compile-time constants
    let offset_vals: Vec<String> = spec.offsets.iter().map(|o| o.to_string()).collect();
    let offset_array = format!("    const int offsets[{}] = {{{}}};",
        n_offsets, offset_vals.join(", "));

    // Generate output parameter list
    let mut output_params = String::new();
    for i in 0..n_outputs {
        output_params += &format!("    double* __restrict__ out{},\n", i);
    }

    // Generate gather code
    let mut gather_code = String::new();
    gather_code += &format!("    double vals[{}];\n", n_offsets);
    gather_code += "    for (int k = 0; k < n_offsets; k++) {\n";
    gather_code += "        int src = gid + offsets[k];\n";
    gather_code += "        vals[k] = (src >= 0 && src < n) ? input[src] : center;\n";
    gather_code += "    }\n";

    // Generate intermediate computations as needed
    let mut intermediates = String::new();

    if spec.needs_local_mean() {
        intermediates += "\n    // Local mean\n";
        intermediates += "    double local_mean = 0.0;\n";
        intermediates += &format!("    for (int k = 0; k < {}; k++) local_mean += vals[k];\n", n_offsets);
        intermediates += &format!("    local_mean /= (double){};\n", n_offsets);
    }

    if spec.needs_local_std() {
        intermediates += "\n    // Local std\n";
        intermediates += "    double local_var = 0.0;\n";
        intermediates += &format!("    for (int k = 0; k < {}; k++) {{\n", n_offsets);
        intermediates += "        double d = vals[k] - local_mean;\n";
        intermediates += "        local_var += d * d;\n";
        intermediates += "    }\n";
        intermediates += &format!("    double local_std = sqrt(local_var / (double){});\n", n_offsets);
    }

    if spec.needs_slope() {
        // Linear regression: slope = cov(offset, val) / var(offset)
        // Offsets are compile-time constants, so offset_mean and offset_var are known.
        let offset_sum: f64 = spec.offsets.iter().map(|o| *o as f64).sum();
        let offset_mean = offset_sum / n_offsets as f64;
        let offset_var: f64 = spec.offsets.iter()
            .map(|o| { let d = *o as f64 - offset_mean; d * d })
            .sum::<f64>();

        intermediates += "\n    // Slope (linear regression over offsets)\n";
        intermediates += "    double slope_num = 0.0;\n";
        intermediates += &format!("    const double offset_mean = {:.6};\n", offset_mean);
        intermediates += &format!("    for (int k = 0; k < {}; k++) {{\n", n_offsets);
        intermediates += "        slope_num += ((double)offsets[k] - offset_mean) * (vals[k] - local_mean);\n";
        intermediates += "    }\n";
        intermediates += &format!("    double slope = slope_num / {:.6};\n", offset_var);
    }

    if spec.needs_peak() {
        intermediates += "\n    // Peak detection\n";
        intermediates += "    int is_peak = 1;\n";
        intermediates += "    int is_valley = 1;\n";
        intermediates += &format!("    for (int k = 0; k < {}; k++) {{\n", n_offsets);
        intermediates += "        if (vals[k] >= center) is_peak = 0;\n";
        intermediates += "        if (vals[k] <= center) is_valley = 0;\n";
        intermediates += "    }\n";
        intermediates += "    double peak = is_peak ? 1.0 : (is_valley ? -1.0 : 0.0);\n";
    }

    // Generate output writes
    let mut output_writes = String::new();
    for (i, feature) in spec.features.iter().enumerate() {
        let expr = feature.cuda_expr(n_offsets, &spec.offsets);
        output_writes += &format!("        out{}[gid] = {};\n", i, expr);
    }

    // Feature names as comment
    let feature_names: Vec<String> = spec.features.iter()
        .map(|f| f.name(&spec.offsets))
        .collect();

    format!(
        r#"// Local context kernel: gather + fused features
// Offsets: {:?}
// Features ({}): {}
// Generated by winrapids-local (Rust)

extern "C" __global__ void local_context(
    const double* __restrict__ input,
{output_params}    int n
) {{
    int gid = blockIdx.x * blockDim.x + threadIdx.x;
    if (gid >= n) return;

    const int n_offsets = {n_offsets};
{offset_array}

    double center = input[gid];

    // Gather: read all offset values
{gather_code}
{intermediates}
    // Write outputs
    {{
{output_writes}    }}
}}
"#,
        spec.offsets,
        n_outputs,
        feature_names.join(", "),
        output_params = output_params,
        n_offsets = n_offsets,
        offset_array = offset_array,
        gather_code = gather_code,
        intermediates = intermediates,
        output_writes = output_writes,
    )
}
