#!/usr/bin/env python
"""
Campsite 2.5 / 2.10 / 2.13 / 2.17 / 2.18 / 2.19 infrastructure.

Generate ALL the numerical constants that tambear-libm's .tam kernels will
embed as hex-bit-pattern literals. These are computed once, at high precision,
from first principles in mpmath, and committed to libm-constants.toml as the
authoritative source.

The path the constants travel:
    1. This script computes each constant via mpmath at 100 digits.
    2. Round to fp64 (nearest, ties-to-even — the default).
    3. Extract the fp64 bit pattern via struct pack/unpack.
    4. Emit as a hex literal in TOML, plus its decimal representation and a
       50-digit-precision reference for audit.
    5. Pathmaker's .tam text-emitter reads this TOML and produces const.f64
       ops with the exact 0x<16hex> bit literal.

No fp64 constant in tambear-libm should be written as a decimal literal in
the .tam text. Every constant goes through this script.

I1/I8 compliance: every constant is computed from the mathematical definition
in mpmath. No libm is consulted. No constants are copied from glibc/musl/
fdlibm/sun-libm. The hex bit pattern is the result of mpmath→fp64 rounding,
which is an IEEE 754 operation, not a libm call.

USAGE
-----
    uv venv
    uv pip install mpmath
    python gen-constants.py > libm-constants.toml
"""
from __future__ import annotations

import io
import struct
import sys

try:
    import mpmath as mp
except ImportError:
    sys.exit("mpmath not installed; run `uv pip install mpmath`")

# Force UTF-8 stdout on Windows so math symbols in comments render correctly.
# Required because Windows cp1252 cannot encode U+2248 (approx) or similar.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
else:
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

mp.mp.dps = 100


def fp64_bits(v: "mp.mpf") -> int:
    """Round an mpmath value to nearest fp64, return its 64-bit pattern as int."""
    f = float(v)
    return struct.unpack("<Q", struct.pack("<d", f))[0]

def fp64(v: "mp.mpf") -> float:
    return float(v)

def hex_lit(v: "mp.mpf") -> str:
    return f"0x{fp64_bits(v):016x}"

def fp64_of_bits(bits: int) -> "mp.mpf":
    """Inverse of fp64_bits: take a bit pattern, return the mpmath value."""
    f = struct.unpack("<d", struct.pack("<Q", bits))[0]
    return mp.mpf(f)

def split_into_hi_lo(
    value_mp: "mp.mpf",
    n_low_zero_mantissa_bits: int,
) -> tuple["mp.mpf", "mp.mpf"]:
    """Split a high-precision mpmath value into (hi, lo) two fp64 pieces, where
    hi has its lowest `n_low_zero_mantissa_bits` of its 52-bit mantissa forced
    to zero. This is the Cody-Waite dual-constant pattern:

        hi + lo  ≈  value  to full (2 * fp64 - n_low_zero_mantissa_bits) bits
        n * hi    is exact in fp64 for |n| < 2^n_low_zero_mantissa_bits

    We compute it by first rounding `value` to fp64, then masking the low
    mantissa bits to zero in the bit representation.
    """
    rounded_bits = fp64_bits(value_mp)
    # Mask: zero out the lowest n_low_zero_mantissa_bits bits of the mantissa
    mask = (~((1 << n_low_zero_mantissa_bits) - 1)) & ((1 << 64) - 1)
    hi_bits = rounded_bits & mask
    hi_mp = fp64_of_bits(hi_bits)
    lo_mp = mp.mpf(value_mp - hi_mp)  # the residual, also rounded to fp64
    # Re-round lo to fp64
    lo_bits = fp64_bits(lo_mp)
    lo_mp = fp64_of_bits(lo_bits)
    return hi_mp, lo_mp


# -- The constants -----------------------------------------------------------

def emit(name: str, value: "mp.mpf", comment: str):
    print(f"[{name}]")
    print(f'comment = "{comment}"')
    print(f'hex = "{hex_lit(value)}"')
    print(f"f64 = {fp64(value)!r}")
    print(f'decimal_50 = "{mp.nstr(value, 50)}"')
    print()


def emit_split(hi_name: str, lo_name: str, value_mp: "mp.mpf", n_low_zero: int, target_name: str):
    hi, lo = split_into_hi_lo(value_mp, n_low_zero)
    residual_check = value_mp - (hi + lo)
    print(f"# Cody-Waite split of {target_name}:")
    print(f"#   {target_name} = {hi_name} + {lo_name}")
    print(f"#   {hi_name} has trailing {n_low_zero} mantissa bits zero, so")
    print(f"#   n * {hi_name} is exact in fp64 for |n| < 2^{n_low_zero} = {1<<n_low_zero}")
    print(f"#   residual |{target_name} - ({hi_name} + {lo_name})| = {mp.nstr(abs(residual_check), 6)}")
    print()
    emit(hi_name, hi, f"{target_name} high part ({n_low_zero} trailing mantissa bits zero)")
    emit(lo_name, lo, f"{target_name} low correction")


def main():
    print("# tambear-libm — authoritative numerical constants")
    print("# Generated by peak2-libm/gen-constants.py from mpmath at 100-digit precision.")
    print("# Do NOT hand-edit. Re-run gen-constants.py if the spec changes.")
    print("#")
    print("# Every entry has:")
    print("#   hex           — the fp64 bit pattern as a 0x<16hex> literal, used by .tam")
    print("#   f64           — the Python repr of the rounded value (for human debugging)")
    print("#   decimal_50    — the mpmath 50-digit decimal representation (audit trail)")
    print("#")
    print("# Invariant I8: every value here is computed from mpmath at 100 digits,")
    print("# not copied from any vendor libm source.")
    print()

    # ----- ln(2) for exp range reduction -----
    ln2 = mp.log(2)
    # For exp: |n| ≤ 1024 in the normal range; we need n_low_zero ≥ 11.
    # Use 12 to have some margin and make n_low_zero a round number of half-words.
    emit_split("ln2_hi", "ln2_lo", ln2, n_low_zero=12, target_name="ln(2)")

    # ----- 1/ln(2) for the multiplier in exp's range reduction -----
    one_over_ln2 = 1 / ln2
    emit("one_over_ln2", one_over_ln2, "1 / ln(2), used for n = round(x * one_over_ln2)")

    # ----- exp overflow and underflow thresholds -----
    # x_overflow: the largest x for which exp(x) is finite in fp64.
    # exp(x_overflow) = fp64_max * (1 - small_margin). We take the safe value
    # x_overflow = ln(fp64_max) - small_epsilon, choosing small_epsilon so that
    # the result is just below the overflow threshold.
    fp64_max_mp = mp.mpf("1.7976931348623157e308")
    fp64_min_normal_mp = mp.mpf("2.2250738585072014e-308")
    fp64_min_denormal_mp = mp.mpf("4.9406564584124654e-324")

    # Exact overflow edge: exp(x) = fp64_max  ⇒  x = ln(fp64_max)
    x_overflow = mp.log(fp64_max_mp)
    emit("x_overflow", x_overflow,
         "exp(x_overflow) ≈ fp64_max; exp(x > this) returns +inf")

    # Exact underflow edge: exp(x) = fp64_min_denormal / 2  ⇒  x = ln(fp64_min_denormal / 2)
    # Below this, the result rounds to +0.
    x_underflow = mp.log(fp64_min_denormal_mp / 2)
    emit("x_underflow", x_underflow,
         "exp(x_underflow) ≈ smallest-representable subnormal; exp(x < this) returns +0")

    # Also the boundary at which subnormal output starts:
    x_subnormal_begin = mp.log(fp64_min_normal_mp)
    emit("x_subnormal_begin", x_subnormal_begin,
         "for x_underflow < x < x_subnormal_begin, exp(x) is subnormal")

    # ----- π/2 for trig range reduction, three-term Cody-Waite -----
    pi = mp.pi
    pi_over_2 = pi / 2

    # For three-term split covering |x| ≤ 2^30:
    # piover2_hi: top ~30 bits of π/2, rest zeros, so n * piover2_hi exact for |n| < 2^30
    # piover2_mid: next chunk
    # piover2_lo: rest
    # We want |n| ≤ 2^30, so hi needs 30 trailing zero mantissa bits.
    pi2_hi_bits = fp64_bits(pi_over_2) & (~((1 << 30) - 1) & ((1 << 64) - 1))
    pi2_hi = fp64_of_bits(pi2_hi_bits)
    pi2_rest = pi_over_2 - pi2_hi

    # Split pi2_rest into mid + lo: mid has 30 trailing zero mantissa bits.
    pi2_mid_bits = fp64_bits(pi2_rest) & (~((1 << 30) - 1) & ((1 << 64) - 1))
    pi2_mid = fp64_of_bits(pi2_mid_bits)
    pi2_lo = pi2_rest - pi2_mid
    pi2_lo = fp64_of_bits(fp64_bits(pi2_lo))

    print("# Three-term Cody-Waite split of π/2:")
    print("#   π/2 = piover2_hi + piover2_mid + piover2_lo")
    print("#   piover2_hi has 30 trailing mantissa bits zero, so n * piover2_hi")
    print("#   is exact in fp64 for |n| < 2^30 = 1073741824 (~1e9)")
    print("#   Supports sin/cos for |x| ≤ 2^30")
    residual_trig = pi_over_2 - (pi2_hi + pi2_mid + pi2_lo)
    print(f"#   residual |π/2 - (hi+mid+lo)| = {mp.nstr(abs(residual_trig), 6)}")
    print()

    emit("piover2_hi", pi2_hi, "π/2 high part (30 trailing mantissa bits zero)")
    emit("piover2_mid", pi2_mid, "π/2 mid part (30 trailing mantissa bits zero)")
    emit("piover2_lo", pi2_lo, "π/2 low correction")

    # ----- 2/π for trig range reduction multiplier -----
    two_over_pi = 2 / pi
    emit("two_over_pi", two_over_pi,
         "2 / π, used for k = round(x * two_over_pi) in sin/cos")

    # ----- π for large-argument tests and atan2 quadrant constants -----
    emit("pi", pi, "π (for tests and atan2 quadrants)")
    emit("three_pi_over_4", 3 * pi / 4, "3π/4 (for atan2)")
    emit("neg_three_pi_over_4", -3 * pi / 4, "-3π/4 (for atan2)")

    # ----- log function constants -----
    # sqrt(2) threshold for log's m-shift
    sqrt2 = mp.sqrt(2)
    emit("sqrt2", sqrt2, "√2, the m-shift threshold in log: if m ≥ √2, divide by 2 and increment e")

    # log(2) for log's reassembly -- same as ln2 above, but we emit a separate
    # named constant so the log implementation doesn't depend on the exp
    # constants file. (The bit pattern is identical.)
    emit("log_ln2_hi", split_into_hi_lo(ln2, 12)[0],
         "ln(2) high part for log reassembly (same as ln2_hi, re-emitted for log's TOML)")
    emit("log_ln2_lo", split_into_hi_lo(ln2, 12)[1],
         "ln(2) low correction for log reassembly")

    # 52 * ln(2), for log's subnormal scaling path
    emit("fifty_two_ln2", 52 * ln2,
         "52 * ln(2), the correction for log's subnormal input path (scale x by 2^52 first)")

    # ----- atan constants -----
    emit("tan_pi_over_8", mp.tan(pi / 8),
         "tan(π/8) = √2 - 1, the reduction threshold for atan: if |x| > this, "
         "apply the shift atan(x) = π/4 + atan((x-1)/(x+1))")

    # π/4 for atan's shift reassembly, Cody-Waite split
    pi_over_4 = pi / 4
    emit_split("pi_over_4_hi", "pi_over_4_lo", pi_over_4, n_low_zero=12,
               target_name="π/4")

    # ----- Round-to-nearest magic number for exp/sin/cos -----
    # The magic-number rounding trick: y_rounded = (y + 1.5·2^52) - 1.5·2^52
    # This produces round-to-nearest-ties-to-even in pure fp64 arithmetic for
    # |y| < 2^52. Used in exp and sin/cos when f64_to_i32_rne is not available.
    magic = mp.mpf("3") * mp.mpf(2) ** 51  # = 1.5 * 2^52
    emit("round_to_int_magic", magic,
         "1.5·2^52 = 6755399441055744.0; used for round-to-nearest-ties-to-even via "
         "the (x + magic) - magic trick when f64_to_i32_rne is unavailable")
    emit("round_to_int_magic_neg", -magic,
         "-1.5·2^52, the signed variant for negative x")

    # ----- 2^-1022 (smallest normal fp64) and related scaling factors -----
    emit("two_to_neg_1022", mp.mpf(2) ** -1022,
         "fp64 smallest positive normal value, used for exp's subnormal two-step scaling")
    emit("two_to_pos_1022", mp.mpf(2) ** 1022,
         "fp64 large scaling constant for subnormal output path")
    emit("two_to_pos_52", mp.mpf(2) ** 52,
         "2^52, used for log's subnormal input pre-scaling")
    emit("one_half", mp.mpf("0.5"), "exactly 1/2, used in several polynomial forms")


if __name__ == "__main__":
    main()
